// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Ver perfil",
  description: "Retorna o perfil da usu\xE1ria atualmente autenticada no Unicost IA (nome, e-mail, cidade, estado, profiss\xE3o).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticada." }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("nome, email, cidade, estado, profissao").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/calculate-fabric.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var systemPrompt = `Voc\xEA \xE9 uma costureira profissional com 30+ anos de experi\xEAncia.
Responda SEMPRE em portugu\xEAs brasileiro.
Considere tecido com largura padr\xE3o 1,40m-1,50m e margem de 10-15%.

Formato:
\u{1F4D0} METRAGEM NECESS\xC1RIA
[quantidade] de tecido (largura 1,50m)
[detalhamento]

\u{1F9F5} TECIDOS RECOMENDADOS
1. [tecido] - [motivo]
2. [tecido] - [motivo]

\u2702\uFE0F DICAS DE CONFEC\xC7\xC3O
\u2022 [dica 1]
\u2022 [dica 2]`;
var calculate_fabric_default = defineTool2({
  name: "calculate_fabric",
  title: "Calcular metragem de tecido",
  description: "Calcula a quantidade de tecido necess\xE1ria para uma pe\xE7a a partir das medidas corporais e recomenda tecidos ideais.",
  inputSchema: {
    peca: z.string().min(1).max(500).describe("Pe\xE7a desejada, ex: 'vestido longo god\xEA'."),
    medidas: z.string().min(1).max(2e3).describe("Medidas corporais (busto, cintura, quadril, comprimento, etc)."),
    tipoMedida: z.string().max(100).optional().describe("Tipo de medida, ex: 'adulto feminino'.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ peca, medidas, tipoMedida }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticada." }], isError: true };
    }
    const key = process.env.LOVABLE_API_KEY;
    if (!key) {
      return { content: [{ type: "text", text: "LOVABLE_API_KEY ausente." }], isError: true };
    }
    const resp = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          {
            role: "user",
            content: `Tipo: ${tipoMedida ?? "n\xE3o informado"}
Medidas: ${medidas}
Pe\xE7a: ${peca}

Calcule a metragem e recomende tecidos.`
          }
        ]
      })
    });
    if (!resp.ok) {
      const t = await resp.text();
      return { content: [{ type: "text", text: `Erro no gateway (${resp.status}): ${t.slice(0, 300)}` }], isError: true };
    }
    const data = await resp.json();
    const text = data.choices?.[0]?.message?.content ?? "";
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/ask-sewing-assistant.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var systemPrompt2 = `Voc\xEA \xE9 uma costureira profissional com 30+ anos de experi\xEAncia em ateli\xEA feminino no Brasil.
Responda SEMPRE em portugu\xEAs brasileiro, de forma pr\xE1tica e direta.
Especialidades: c\xE1lculo de tecido, modelagem (god\xEA, evas\xEA, reta), tecidos ideais, acabamento, precifica\xE7\xE3o, medidas.
Use markdown e emojis (\u{1F4D0} \u2702\uFE0F \u{1F9F5} \u{1F4A1}) quando ajudar.`;
var ask_sewing_assistant_default = defineTool3({
  name: "ask_sewing_assistant",
  title: "Perguntar \xE0 assistente de costura",
  description: "Faz uma pergunta livre \xE0 assistente de costura do Unicost IA (tecidos, modelagem, metragem, precifica\xE7\xE3o, dicas).",
  inputSchema: {
    question: z2.string().min(1).max(5e3).describe("Pergunta em portugu\xEAs.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ question }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticada." }], isError: true };
    }
    const key = process.env.LOVABLE_API_KEY;
    if (!key) {
      return { content: [{ type: "text", text: "LOVABLE_API_KEY ausente." }], isError: true };
    }
    const resp = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt2 },
          { role: "user", content: question }
        ]
      })
    });
    if (!resp.ok) {
      const t = await resp.text();
      return { content: [{ type: "text", text: `Erro no gateway (${resp.status}): ${t.slice(0, 300)}` }], isError: true };
    }
    const data = await resp.json();
    const text = data.choices?.[0]?.message?.content ?? "";
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hpbillqujaculclavwkc";
var mcp_default = defineMcp({
  name: "unicost-ia-mcp",
  title: "Unicost IA MCP",
  version: "0.1.0",
  instructions: "Ferramentas do Unicost IA (Atelieh M\xE3ezinha): consultar perfil da costureira, calcular metragem de tecido para pe\xE7as e conversar com a assistente de costura IA.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, calculate_fabric_default, ask_sewing_assistant_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
